name: First Cron Job

       # Controls when the workflow will run
on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "40 15 * * *"

     # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
      # Runs a single command using the runners shell
    steps:
     - name: Deploy Stage
       uses: fjogeleit/http-request-action@v1
       with:
        url: 'https://clockify-6tv6.onrender.com/api/clockify'
        method: 'GET'
